apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-voting-app-config
  labels:
    app: azure-voting-app
data:
  config_file.cfg: |
    # UI Configurations
    TITLE = 'Azure Voting App'
    VOTE1VALUE = 'Cats'
    VOTE2VALUE = 'Dogs'
    SHOWHOST = 'false'
